Class cjs.interopway.rest.samples.bo.DeleteUserResponse Extends (%Persistent, cjs.interopway.rest.bo.PatchResponse)
{

Storage Default
{
<Data name="DeleteUserResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>ResponseDTO</Value>
</Value>
</Data>
<DataLocation>^cjs.interoD7D1.DeleteUserRC17AD</DataLocation>
<DefaultData>DeleteUserResponseDefaultData</DefaultData>
<IdLocation>^cjs.interoD7D1.DeleteUserRC17AD</IdLocation>
<IndexLocation>^cjs.interoD7D1.DeleteUserRC17AI</IndexLocation>
<StreamLocation>^cjs.interoD7D1.DeleteUserRC17AS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
