Class cjs.interopway.rest.samples.bo.GetUserResponse Extends (%Persistent, cjs.interopway.rest.bo.GetResponse)
{

Storage Default
{
<Data name="GetUserResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>ResponseDTO</Value>
</Value>
</Data>
<DataLocation>^cjs.interoD7D1.GetUserResp5FB7D</DataLocation>
<DefaultData>GetUserResponseDefaultData</DefaultData>
<IdLocation>^cjs.interoD7D1.GetUserResp5FB7D</IdLocation>
<IndexLocation>^cjs.interoD7D1.GetUserResp5FB7I</IndexLocation>
<StreamLocation>^cjs.interoD7D1.GetUserResp5FB7S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
