Class cjs.interopway.rest.samples.bo.PatchUserResponse Extends (%Persistent, cjs.interopway.rest.bo.PatchResponse)
{

Storage Default
{
<Data name="PatchUserResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>ResponseDTO</Value>
</Value>
</Data>
<DataLocation>^cjs.interoD7D1.PatchUserReB938D</DataLocation>
<DefaultData>PatchUserResponseDefaultData</DefaultData>
<IdLocation>^cjs.interoD7D1.PatchUserReB938D</IdLocation>
<IndexLocation>^cjs.interoD7D1.PatchUserReB938I</IndexLocation>
<StreamLocation>^cjs.interoD7D1.PatchUserReB938S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
