Class cjs.interopway.rest.samples.bo.PostUserResponse Extends (%Persistent, cjs.interopway.rest.bo.PostResponse)
{

Storage Default
{
<Data name="PostUserResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>RequestDTO</Value>
</Value>
<Value name="3">
<Value>ResponseDTO</Value>
</Value>
</Data>
<DataLocation>^cjs.interoD7D1.PostUserResABB4D</DataLocation>
<DefaultData>PostUserResponseDefaultData</DefaultData>
<IdLocation>^cjs.interoD7D1.PostUserResABB4D</IdLocation>
<IndexLocation>^cjs.interoD7D1.PostUserResABB4I</IndexLocation>
<StreamLocation>^cjs.interoD7D1.PostUserResABB4S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
