Class cjs.interopway.rest.samples.bo.PutUserResponse Extends (%Persistent, cjs.interopway.rest.bo.PutResponse)
{

Storage Default
{
<Data name="PutUserResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>ResponseDTO</Value>
</Value>
</Data>
<DataLocation>^cjs.interoD7D1.PutUserResp81F1D</DataLocation>
<DefaultData>PutUserResponseDefaultData</DefaultData>
<IdLocation>^cjs.interoD7D1.PutUserResp81F1D</IdLocation>
<IndexLocation>^cjs.interoD7D1.PutUserResp81F1I</IndexLocation>
<StreamLocation>^cjs.interoD7D1.PutUserResp81F1S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
